# Gemfile
source 'https://rubygems.org'

gem 'sinatra'
# Required to use some advanced features of# Sinatra, like namespaces
# gem 'sinatra-contrib'
gem 'thin'
gem 'puma'
gem 'reel'
gem 'http'
gem 'webrick'
gem 'rake'
gem 'rack-test'
gem 'test-unit'